worker_processes  1;

events {
    worker_connections  1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile        on;
    keepalive_timeout  65;

    server {
        listen       80;
        server_name  goi-cds.magazineluiza.intranet goi-cds asc-ops-cds-01.magazineluiza.intranet;

        # 1. Quando o usuário digitar apenas o domínio, manda para /home
        location = / {
            return 301 http://$host/home;
        }

        # 2. Encaminha TODO o resto para o Flask (127.0.0.1:8080)
        location / {
            proxy_pass http://127.0.0.1:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            # Importante: O Flask pode precisar disso para redirecionamentos internos
            proxy_redirect off;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }
    }
}